### PR TITLE
Add ability to use login links to add accounts

### PR DESCRIPTION
**Pull request by DarkionAvey**
Hi

Thanks for the awesome app! I just found it on F-droid and I am really stoked about it. Unfortunately, my Instagram account doesn't have a password (for some reason). I can only login through "login links" or using Facebook. 

This pull request adds the ability to use login links to add accounts. Those links are sent to you via sms and can log you in directly without password, through your default web browser, thus bypassing barinsta webview. This pull-request fixes this issue by allowing the user to paste the link into barinsta.

Maybe as a suggestion, barinsta should directly handle https://ig.me links

Thank you

### CODE REVIEW

**Comment by austinhuang0131** [comment]
I can't test this because Instagram either redirects me to homepage or a Facebook error page...

**Comment by DarkionAvey** [comment]
> I can't test this because Instagram either redirects me to homepage or a Facebook error page...

This pull-request doesn't fix Facebook login, it only fixes login links. You can get a login link by clicking "forgot password?". You will be sent a link to your email, or phone via sms

**Comment by austinhuang0131** [comment]
Yes, I did that, and it does redirect to a Facebook error page

**Comment by DarkionAvey** [comment]
🤔 I am not sure. My account is not associated with an email, only with a phone number. Maybe your account is not associated with a phone number?

**Comment by austinhuang0131** [comment]
I have a phone number and an email

I get nothing on the email

I get a message on SMS, but the link is invalid

**Comment by DarkionAvey** [comment]
why is the link invalid? does it start with ig.me/

**Comment by austinhuang0131** [comment]
Yes it starts with ig.me but when I do it it either redirects to homepage or gives me a Facebook error page...

**Comment by austinhuang0131** [comment]
Actually @sigaloid you wanna try testing this PR? (Remember to update from master before testing it)

**Comment by sigaloid** [comment]
I do not have this type of account, just a regular password account, so is there anything I can do to test?

**Comment by austinhuang0131** [comment]
"Forget password"

**Comment by sigaloid** [comment]
Will try to log in by clicking forgot password, how do I compile?

**Comment by austinhuang0131** [comment]
How did you compile master last time

**Comment by sigaloid** [comment]
I didn't, I waited for a release lol

**Comment by austinhuang0131** [comment]
oh nvm then

**Comment by DarkionAvey** [comment]
I'm going to close this PR. You can refer back to it once the issue is raised by someone else.

**Pull request closed without merging**
