### PR TITLE
DM update

### PR DESCRIPTION
**Pull request by ammargitham**
This is still WIP!

Contrary to the branch name, the notification part is not yet been implemented. Lot of stuffs are incomplete.

The reason for creating the PR is because the changes are required outside the dm package, so others can be aware of it.

### CODE REVIEW

**Comment by austinhuang0131** [comment]
close #480

**Comment by austinhuang0131** [comment]
manually close #583 after merge

**Comment by Rexogamer** [comment]
> reminder for me to manually close #583 after merge

~~just say "closes #583"~~

**Comment by austinhuang0131** [comment]
why u stalking my github activity

closes #583

**Comment by Rexogamer** [comment]
I'm watching the repo you fool, also oof

**Comment by austinhuang0131** [comment]
^ to close those issues as well

**Pull request merged**
