### PR TITLE
Update strings.xml (ptbr)

### PR DESCRIPTION
**Pull request by cizordj**
- Update portuguese translation

### CODE REVIEW

**Comment by austinhuang0131** [comment]
In the future, you are required to use [Crowdin](https://crowdin.com/project/instagrabber).

But, seeing that you are probably doing this for Hacktoberfest, I'll keep it open this time.

**Comment by cizordj** [comment]
@RickyM7 sim eu entendo. Eu só traduzi a palavra becape porque ela existe na língua portuguesa e é mais confortável de ler do que "backup"

Eu pesquisei ela no minidicionário do Celso Pedro Luft e desde então uso ela em tudo o que escrevo. Sobre o resto vocês podem editar o commit. O que eu queria na verdade era achar aquelas strings em inglês pra terminar de traduzir, eu tô usando o velho Instagrabber e volta e meia me deparo com alguns trechos em inglês, o problema é que esse aqui foi o único lugar que eu encontrei pra fazer as traduções.

In English:
Yes I got you, I only translated backup because this word really exists in portuguese and it's more comfortable to read.

I looked it up in the CPL's dictionary and since then I use it whenever I can. About the rest, you guys can edit my PR and take off what is unnecessary. What I really wanted to do actually was to find strings in English and translate them all, I am using the good-old Instagrabber and sometimes I see untranslated messages popping up on my screen, the only problem is that I couldn't find those strings here on github.

I'll stick with @austinhuang0131's advice and try to use crowdin.

**Comment by RickyM7** [comment]
@cizordj I understand, however I found the word "Becape" strange, but the sense is the same, so it's not a problem to change. Besides, if you want I can make the changes in Crowdin, but I will do according to what I mentioned, that is, I will try to make the most faithful to the original text. What do you think?

**Comment by cizordj** [comment]
@RickyM7 It's okay for me, you can make the changes.

**Comment by RickyM7** [comment]
@cizordj Done. Based on your changes I've made other changes to make the translation as consistent as possible. If you find other errors in the future, you can tell me to make the change in Crowdin.

**Pull request closed without merging**
