### PR TITLE
BottomNavigationView redesign 

### PR DESCRIPTION
**Pull request by vojta-horanek**
I find the BottomNavigationView icons and styling very confusing and since it's the main navigation component, it should be clear as day. For that I propose these changes:

- making the labels automatically hide
  - this removes some clutter from the app IMHO
  - this is the [default behavior for more than 4 items](https://developer.android.com/reference/com/google/android/material/bottomnavigation/LabelVisibilityMode) and I think we should keep it here to move the focus from some text in the navigation bar to the actual content
  - labels are always shown when the user is logged out, since there are only 2 items
- changing the order and the default selected item
  - the "feed" is now in the center for better orientation. this could be moved to the left like the official Instagram app (I put it in the center because profile screen (which was the default) was there)
  - the feed should really be the default screen since it's the screen the user interacts with the most. I don't understand why the profile screen is shown at start by default (only valid for egoists lol)
- changing the feed icon to "home"
  - this makes sense since the feed is now the default screen
  - this copies the official Instagram app and looks a lot cleaner and a lot less confusing
- changing the messages icon to "message"
  - really just looks better, the current icon ("send") should only be used as an action/button
- changing the discover icon to "explore"
  - also looks better and makes sense a lot more IMHO
-  changing the profile icon to "person"
   - this is the least important change, but I think it still makes sense
   - the "person" icon shows a person without a circle thus representing the "entire person" rather than focusing on the persons element (profile picture)
   - the old icon in "Layout" still makes sense since it represents the profile picture, not the person itself
 
**Logged in**  

Screenshot_1611102366
**Logged out**  

Screenshot_1611102448

Any critique is welcome, this PR is based on my opinions. I'm happy to change anything to make this PR possible.

### CODE REVIEW

**Comment by vojta-horanek** [comment]
I just now saw there is already a PR for BottomNavigationView, these will probably not be compatible :(

**Comment by austinhuang0131** [comment]
> I don't understand why the profile screen is shown at start by default (only valid for egoists lol)

So you don't get to see feed right away so to hopefully reduce addiction (as presented [here](https://github.com/humanetech-community/awesome-humane-tech/pull/29)), but it's customizable in settings, so...

> changing the feed icon to "home"

...you can't always say feed is home.

Actually, have you tried making the tab order customizable (and possibly add notification as an option (because some people still want to be addicted by choice, shrug))?

I'll prioritize this PR over #607 since the other one simply proposes more fixed choices

**Comment by ammargitham** [comment]
@vojta-horanek Have you tried making the order configurable?

**Comment by ammargitham** [comment]
I am continuing this PR in https://github.com/ammargitham/barinsta/tree/bottombar_redesign

**Comment by ammargitham** [comment]
Continued in #850

**Pull request closed without merging**
