### PR TITLE
SplashActivity for no internet

### PR DESCRIPTION
**Pull request by snajdovski**
Added SplashActivity that checks if internet is present, with great UI ofc, and added one other activity that is displayed when there is no internet.
Note: Dark theme doesn't work for some reason I dont understand how it is beign applied.

### CODE REVIEW

**Comment by ammargitham** [comment]
Hi @snajdovski, instead of a new activity for the splash screen, can you use the windowBackground method? So that the splash screen will be displayed only for a cold start and not each time.

**Comment by snajdovski** [comment]
> Hi @snajdovski, instead of a new activity for the splash screen, can you use the windowBackground method? So that the splash screen will be displayed only for a cold start and not each time.

Sure, I could do that

**Comment by snajdovski** [comment]
> > Hi @snajdovski, instead of a new activity for the splash screen, can you use the windowBackground method? So that the splash screen will be displayed only for a cold start and not each time.
> 
> Sure, I could do that

But than it will kill off the logic of using Network checks on start right?

**Comment by snajdovski** [comment]
> Hi @snajdovski, instead of a new activity for the splash screen, can you use the windowBackground method? So that the splash screen will be displayed only for a cold start and not each time.

The Activity also is being used to Check for the Internet if there is no Internet it just displays noInternetConnectionActivity

**Comment by ammargitham** [comment]
> But than it will kill off the logic of using Network checks on start right?

Yeah. But checking internet connection only at start is kind of incomplete. What I had in mind was to have a [broadcast receiver](https://developer.android.com/training/basics/network-ops/managing#detect-changes) to check for connectivity changes and show a snackbar if there is not connectivity.

So what can be done is instead of an activity, use fragments. If in MainActivity there is no connectivity we can show the fragment for no activity, otherwise if the network is lost in between show a snackbar.

**Comment by snajdovski** [comment]
> > But than it will kill off the logic of using Network checks on start right?
> 
> Yeah. But checking internet connection only at start is kind of incomplete. What I had in mind was to have a [broadcast receiver](https://developer.android.com/training/basics/network-ops/managing#detect-changes) to check for connectivity changes and show a snackbar if there is not connectivity.
> 
> So what can be done is instead of an activity, use fragments. If in MainActivity there is no connectivity we can show the fragment for no activity, otherwise if the network is lost in between show a snackbar.

Maybe when I have more time I will make a simple lib that measures the actual download speed (ping) in background and report back to user that their internet is slow or not present.

**Comment by snajdovski** [comment]
> > > But than it will kill off the logic of using Network checks on start right?
> > 
> > 
> > Yeah. But checking internet connection only at start is kind of incomplete. What I had in mind was to have a [broadcast receiver](https://developer.android.com/training/basics/network-ops/managing#detect-changes) to check for connectivity changes and show a snackbar if there is not connectivity.
> > So what can be done is instead of an activity, use fragments. If in MainActivity there is no connectivity we can show the fragment for no activity, otherwise if the network is lost in between show a snackbar.
> 
> Maybe when I have more time I will make a simple lib that measures the actual download speed (ping) in background and report back to user that their internet is slow or not present.

I have no time for adding this right now I am preoccupied with work on personal projects

**Pull request closed without merging**
