### PR TITLE
Disable scrolling on empty profiles - Fix issues #1093, #1135, #1061

### PR DESCRIPTION
**Pull request by raniapl**
This disables the scrolling on profiles with no posts.
It also adds margin between the chat bubble and bottom controls and increases margin on the right and the bottom of the profile pic download button.

### CODE REVIEW

**Comment by ammargitham** [comment]
https://github.com/austinhuang0131/barinsta/pull/1219/commits/8210347e66907866756d3910b675d83f14895c0f will have to be reverted and adapted for new layout changes in upcoming commits

**Comment by raniapl** [comment]
> [8210347](https://github.com/austinhuang0131/barinsta/commit/8210347e66907866756d3910b675d83f14895c0f) will have to be reverted and adapted for new layout changes in upcoming commits

Thanks for the feedback, I'll on that.

**Comment by ammargitham** [comment]
Have pushed the changes. Just to summarize, the profile details layout has been moved out of collapsing toolbar and now uses MotionLayout to achieve similar effect. So maybe you will have to disabled the transition when there are no posts.

**Comment by ammargitham** [comment]
@raniapl Are you going to update this with the new changes?

**Comment by raniapl** [comment]
> @raniapl Are you going to update this with the new changes?

Yes, I'm sorry, I was a bit busy this week. I hope I'll have done this by tomorrow.

**Comment by raniapl** [comment]
@ammargitham hey, I think I've fixed it and now it works properly with the Motion Layout. Could you review it?
Scrolling is disabled on private or blank profiles. However, in profiles with 1 or 2 posts for example, scrolling is still allowed. Maybe there could be a fix so scrolling on profiles is allowed only when there are more posts to load?

**Comment by ammargitham** [comment]
@raniapl Seems good. For the case when the no. of posts are less and the view should not scroll, we would also need to check if the number is such that the last row of posts are not cut off by the bottom navigation bar. Since in that case the view should scroll. For now, just checking 0 posts is fine.

**Review by ammargitham — APPROVED** [review]

**Pull request merged**
